name: Deno release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32.2

      - name: Compile
        run: |
          deno run -A bundle.ts
          cd out
          chmod u+x cli-gpt
          zip cli-gpt.zip cli-gpt
          rm cli-gpt

      - name: Release and upload artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            out/cli-gpt.zip
