name: Deno release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32.2

      - name: Compile
        run: |
          mkdir -p bin/

          deno compile --output bin/cli-gpt.x86_64-unknown-linux-gnu --target x86_64-unknown-linux-gnu --allow-net --allow-read --allow-env --unstable src/index.ts
          deno compile --output bin/cli-gpt.x86_64-apple-darwin --target x86_64-apple-darwin --allow-net --allow-read --allow-env --unstable src/index.ts
          deno compile --output bin/cli-gpt.aarch64-apple-darwin --target aarch64-apple-darwin --allow-net --allow-read --allow-env --unstable src/index.ts

          cd bin

          zip cli-gpt.x86_64-unknown-linux-gnu.zip cli-gpt.x86_64-unknown-linux-gnu
          zip cli-gpt.x86_64-apple-darwin.zip cli-gpt.x86_64-apple-darwin
          zip cli-gpt.aarch64-apple-darwin.zip cli-gpt.aarch64-apple-darwin

          rm cli-gpt.x86_64-unknown-linux-gnu
          rm cli-gpt.x86_64-apple-darwin
          rm cli-gpt.aarch64-apple-darwin

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            bin/cli-gpt.x86_64-unknown-linux-gnu.zip
            bin/cli-gpt.x86_64-apple-darwin.zip
            bin/cli-gpt.aarch64-apple-darwin.zip
